services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        - INSTALL_DEV=true
    image: ticket_dashboard:latest
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - production_media:/app/ticket_dashboard/media
    ports:
      - "8000:8000"
  qcluster:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        - INSTALL_DEV=true
    image: ticket_dashboard:latest
    command: python manage.py qcluster
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - production_media:/app/ticket_dashboard/media

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    image: ticket_dashboard_postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql
      - postgres_backups:/backups

volumes:
  postgres_data:
  postgres_backups:
  production_media:
