volumes:
  task_dashboard_local_postgres_data: {}
  task_dashboard_local_postgres_data_backups: {}

services:
  # --- 1. Main App (Port 8000) ---
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: task_dashboard_local_django
    container_name: task_dashboard_django
    init: true
    environment:
      USE_DOCKER: ${USE_DOCKER:-yes}
      IPYTHONDIR: ${IPYTHONDIR:-/app/.ipython}
      DJANGO_READ_DOT_ENV_FILE: ${DJANGO_READ_DOT_ENV_FILE:-True}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-default-key-change-me}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      DJANGO_ADMIN_URL: ${DJANGO_ADMIN_URL:-explicit-declared-follow/}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-config.settings.local}
      POSTGRES_USER: ${POSTGRES_USER:-debug}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-debug}
      POSTGRES_DB: ${POSTGRES_DB:-task_dashboard}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DATABASE_URL: postgres://${POSTGRES_USER:-debug}:${POSTGRES_PASSWORD:-debug}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-task_dashboard}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    volumes:
      - /app/.venv
    ports:
      - '8000:8000'

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: task_dashboard_production_postgres
    container_name: task_dashboard_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-debug}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-debug}
      POSTGRES_DB: ${POSTGRES_DB:-task_dashboard}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - task_dashboard_local_postgres_data:/var/lib/postgresql
      - task_dashboard_local_postgres_data_backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-debug} -d ${POSTGRES_DB:-task_dashboard}"]
      interval: 10s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:8
    container_name: task_dashboard_valkey
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
