# Generated by Django 5.2.8 on 2026-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_serviceconfiguration_api_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='api_token',
            field=models.CharField(blank=True, help_text='API Token or Secret for authentication.', max_length=255, null=True),
        ),
    ]
