# Generated by Django 5.2.8 on 2026-01-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_serviceconfiguration_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpermission',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN_ONLY', 'Only own tasks')], default='FULL', help_text='FULL: View everything. LIMITED: View only unassigned tasks or those assigned to the user. OWN_ONLY: View only tasks assigned to the user.', max_length=10),
        ),
    ]
