# Generated by Django 5.2.8 on 2026-01-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_savedview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedview',
            unique_together={('user', 'name')},
        ),
    ]
