# Generated by Django 5.2.8 on 2026-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_savedview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='api_url',
            field=models.URLField(blank=True, default='', help_text='Base URL for the service API.'),
        ),
    ]
