# Generated by Django 5.2.8 on 2026-03-03 23:59

import task_dashboard.users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_task_model_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='api_password',
            field=task_dashboard.users.fields.EncryptedCharField(blank=True, help_text='Password for Basic Authentication (e.g. Eramba)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='api_username',
            field=models.CharField(blank=True, help_text='Username for Basic Authentication (e.g. Eramba)', max_length=255),
        ),
    ]
