# Generated by Django 5.2.8 on 2026-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_serviceconfiguration_api_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
