# Generated by Django 5.2.8 on 2026-03-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_task_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalgroup',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
