# Generated by Django 5.2.8 on 2026-03-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_externalgroup_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='default_access_level',
            field=models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='NONE', help_text='Default access level for all users on this service.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketpermission',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='FULL', help_text='FULL: View everything. LIMITED: View only unassigned tasks or those assigned to the user. OWN: View only tasks assigned to the user. NONE: No access.', max_length=10),
        ),
    ]
