# Generated by Django 5.2.8 on 2026-03-09 09:51

from django.db import migrations

def update_own_only(apps, schema_editor):
    TicketPermission = apps.get_model('users', 'TicketPermission')
    TicketPermission.objects.filter(access_level='OWN_ONLY').update(access_level='OWN')

def revert_own_only(apps, schema_editor):
    TicketPermission = apps.get_model('users', 'TicketPermission')
    TicketPermission.objects.filter(access_level='OWN').update(access_level='OWN_ONLY')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_serviceconfiguration_default_access_level_and_more'),
    ]

    operations = [
        migrations.RunPython(update_own_only, revert_own_only),
    ]
