# Generated by Django 5.2.8 on 2026-03-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0018_update_own_only_to_own'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='TicketPermission',
            new_name='TaskPermission',
        ),
        migrations.AlterField(
            model_name='task',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.serviceconfiguration'),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='django_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_permissions', to='auth.group'),
        ),
        migrations.AlterModelOptions(
            name='taskpermission',
            options={'verbose_name': 'Task Permission', 'verbose_name_plural': 'Task Permissions'},
        ),
    ]
