# Generated by Django 5.2.8 on 2026-03-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0019_rename_models_to_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='FULL', help_text='FULL: View everything. LIMITED: View only unassigned tasks or those assigned to the user. OWN: View only tasks assigned to the user. NONE: No access.', max_length=10)),
                ('django_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_permissions', to='auth.group')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceconfiguration')),
            ],
            options={
                'verbose_name': 'Service Permission',
                'verbose_name_plural': 'Service Permissions',
                'unique_together': {('django_group', 'service')},
            },
        ),
    ]
