# Generated by Django 5.2.8 on 2026-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_servicepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepermission',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='NONE', help_text='FULL: View everything. LIMITED: View only unassigned tasks or those assigned to the user. OWN: View only tasks assigned to the user. NONE: No access.', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='NONE', help_text='FULL: View everything. LIMITED: View only unassigned tasks or those assigned to the user. OWN: View only tasks assigned to the user. NONE: No access.', max_length=10),
        ),
    ]
