# Generated by Django 5.2.8 on 2026-03-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_servicepermission_access_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconfiguration',
            options={'ordering': ['name'], 'permissions': [('view_system_health', 'Can view system health indicator')], 'verbose_name': 'Service Configuration', 'verbose_name_plural': 'Service Configurations'},
        ),
    ]
