# Generated by Django 5.2.8 on 2026-03-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_serviceconfiguration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconfiguration',
            options={'ordering': ['name'], 'permissions': [('view_system_health', 'Can view system health indicator'), ('view_admin_button', 'Can view admin panel button')], 'verbose_name': 'Service Configuration', 'verbose_name_plural': 'Service Configurations'},
        ),
    ]
