# Generated by Django 5.2.8 on 2026-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_globalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='default_task_states',
            field=models.CharField(default='open,pending', help_text='Comma-separated list of default task states to show in the table (e.g., open,pending,new).', max_length=255),
        ),
    ]
