# Generated by Django 5.2.8 on 2026-04-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0025_globalsetting_default_task_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_group', to='auth.group')),
            ],
            options={
                'verbose_name': 'SSO Group Marker',
                'verbose_name_plural': 'SSO Group Markers',
            },
        ),
    ]
