# Generated by Django 5.2.8 on 2026-04-11 17:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_ssogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='search_text',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.F('title'), models.Value(' '), models.F('external_id'), models.Value(' '), models.F('customer'), models.Value(' '), models.F('owner'), models.Value(' '), models.F('group')), output_field=models.TextField()),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['search_text'], name='users_task_search__1d4dc9_idx'),
        ),
    ]
