# Generated by Django 5.2.8 on 2026-04-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_task_search_text_task_users_task_search__1d4dc9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.externalgroup'),
        ),
    ]
