# Generated by Django 5.2.8 on 2026-04-11 18:29

from django.db import migrations

def migrate_task_groups(apps, schema_editor):
    Task = apps.get_model('users', 'Task')
    ExternalGroup = apps.get_model('users', 'ExternalGroup')

    # Unassigned markers to handle gracefully
    unassigned_markers = {None, "", "-", "None", "Unassigned"}

    # Use a cache to avoid repeated lookups
    group_cache = {}

    tasks = Task.objects.select_related('service').all()
    for task in tasks:
        group_name = task.group
        if not group_name or group_name in unassigned_markers:
            continue

        origin = task.service.name
        cache_key = (origin, group_name)

        if cache_key not in group_cache:
            ext_group, _ = ExternalGroup.objects.get_or_create(
                origin=origin,
                name=group_name
            )
            group_cache[cache_key] = ext_group

        task.service_group = group_cache[cache_key]
        task.save(update_fields=['service_group'])

def reverse_migrate_task_groups(apps, schema_editor):
    Task = apps.get_model('users', 'Task')
    Task.objects.all().update(service_group=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_task_service_group'),
    ]

    operations = [
        migrations.RunPython(migrate_task_groups, reverse_migrate_task_groups),
    ]
