# Generated by Django 5.2.8 on 2026-04-13 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_enable_unaccent'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER FUNCTION unaccent(text) IMMUTABLE;",
            reverse_sql="ALTER FUNCTION unaccent(text) STABLE;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_task_owner_array ON users_task USING GIN (regexp_split_to_array(unaccent(lower(owner)), '[^a-z0-9@.-]+'));",
            reverse_sql="DROP INDEX IF EXISTS idx_task_owner_array;"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_task_owner_email_array ON users_task USING GIN (regexp_split_to_array(unaccent(lower(owner_email)), '[^a-z0-9@.-]+'));",
            reverse_sql="DROP INDEX IF EXISTS idx_task_owner_email_array;"
        ),
    ]
