# Generated by Django 5.2.13 on 2026-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_align_owner_gin_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_priority',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='original_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
