# Generated by Django 5.2.13 on 2026-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_task_field_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalgroup',
            options={'ordering': ['origin', 'name'], 'verbose_name': 'External Group', 'verbose_name_plural': 'External Groups'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='externalgroup',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Seen'),
        ),
        migrations.AlterField(
            model_name='externalgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='externalgroup',
            name='origin',
            field=models.CharField(max_length=50, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='company_name',
            field=models.CharField(default='Internal', help_text='Used as fallback customer name across services if none is specified.', max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='default_task_states',
            field=models.CharField(default='open,pending', help_text='Comma-separated list of default task states to show in the table (e.g., open,pending,new).', max_length=255, verbose_name='Default Task States'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='sso_default_group',
            field=models.CharField(blank=True, default='', help_text="Fallback group assigned to SSO users when Keycloak provides no groups. Leave blank to use the built-in 'sso-default-fallback' group.", max_length=150, verbose_name='SSO Default Group'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='api_url',
            field=models.URLField(blank=True, default='', help_text='Base URL for the service API.', verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='default_access_level',
            field=models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='NONE', help_text='Default access level for all users on this service.', max_length=10, verbose_name='Default Access Level'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this service from the dashboard completely.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='name',
            field=models.CharField(help_text='Display Name (e.g. Internal Helpdesk)', max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='service_type',
            field=models.CharField(choices=[('zammad', 'Zammad'), ('gitlab', 'GitLab'), ('espocrm', 'EspoCRM'), ('eramba', 'Eramba'), ('openproject', 'OpenProject')], default='zammad', help_text='Type of service to connect to.', max_length=20, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='external_id',
            field=models.CharField(max_length=255, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(blank=True, max_length=255, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=50, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
