# Generated by Django 5.2.13 on 2026-05-03 00:33

import django.contrib.postgres.indexes
import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_externalgroup_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.RawSQL("regexp_split_to_array(unaccent(replace(replace(replace(lower(owner), 'ö', 'oe'), 'ä', 'ae'), 'ü', 'ue')), '[^a-z0-9@.-]+')", ()), name='task_owner_array_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.RawSQL("regexp_split_to_array(unaccent(replace(replace(replace(lower(owner_email), 'ö', 'oe'), 'ä', 'ae'), 'ü', 'ue')), '[^a-z0-9@.-]+')", ()), name='task_email_array_idx'),
        ),
    ]
