# Generated by Django 5.2.14 on 2026-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_task_task_owner_array_idx_task_task_email_array_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='service_type',
            field=models.CharField(choices=[('zammad', 'Zammad'), ('gitlab', 'GitLab'), ('espocrm', 'EspoCRM'), ('eramba', 'Eramba'), ('openproject', 'OpenProject'), ('kimai', 'Kimai')], default='zammad', help_text='Type of service to connect to.', max_length=20, verbose_name='Service Type'),
        ),
    ]
