# Generated by Django 5.2.14 on 2026-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_kimai_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='kimai_customer_country',
            field=models.CharField(default='DE', help_text='ISO 3166-1 alpha-2 country code used when creating Kimai customers.', max_length=5, verbose_name='Kimai Customer Country'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='kimai_customer_timezone',
            field=models.CharField(default='Europe/Berlin', help_text='Timezone used when creating Kimai customers (e.g. Europe/Berlin).', max_length=64, verbose_name='Kimai Customer Timezone'),
        ),
    ]
