# Generated by Django 5.2.14 on 2026-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_add_kimai_customer_fields_to_globalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='kimai_customer_name',
            field=models.CharField(blank=True, default='', help_text="Override the Kimai customer for all activities from this service. Leave blank to use the task's own customer field, falling back to the global company name.", max_length=100, verbose_name='Kimai Customer Name Override'),
        ),
    ]
