# Generated by Django 5.2.14 on 2026-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_add_kimai_customer_name_to_serviceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='kimai_grace_period_days',
            field=models.IntegerField(default=3, help_text='Business days behind before the Kimai reminder banner triggers.', verbose_name='Kimai Grace Period (days)'),
        ),
    ]
