# Generated by Django 5.2.14 on 2026-05-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_globalsetting_kimai_grace_period_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsetting',
            name='kimai_grace_period_days',
        ),
    ]
