# Generated by Django 5.2.14 on 2026-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_globalsetting_kimai_grace_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='task_fetch_interval_minutes',
            field=models.PositiveIntegerField(default=5, help_text='How often to fetch tasks from all services. Takes effect after saving.', verbose_name='Task Fetch Interval (minutes)'),
        ),
    ]
