# Generated by Django 5.2.14 on 2026-05-26 09:47

import task_dashboard.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_globalsetting_task_fetch_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_days',
            field=models.JSONField(blank=True, default=task_dashboard.users.models._default_working_days),
        ),
    ]
