# Generated by Django 5.2.14 on 2026-05-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_user_working_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconfiguration',
            options={'ordering': ['name'], 'permissions': [('view_system_health', 'Can view system health indicator'), ('view_admin_button', 'Can view admin panel button'), ('view_kimai_overview', 'Can view the Kimai manager overview')], 'verbose_name': 'Service Configuration', 'verbose_name_plural': 'Service Configurations'},
        ),
    ]
