# Generated by Django 5.2.14 on 2026-06-01 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_serviceconfiguration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('kimai_user_id', models.IntegerField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked Django user; empty means this owner is undiscovered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Owner',
                'verbose_name_plural': 'Task Owners',
                'ordering': ['name', 'email'],
            },
        ),
    ]
