# Generated by Django 5.2.14 on 2026-06-01 16:32

import task_dashboard.users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_taskowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Use these SMTP settings instead of the environment defaults.', verbose_name='Enabled')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username')),
                ('password', task_dashboard.users.fields.EncryptedCharField(blank=True, default='', max_length=255, verbose_name='Password')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('default_from_email', models.CharField(blank=True, default='', help_text='e.g. "Task Dashboard <noreply@example.com>".', max_length=255, verbose_name='From Address')),
                ('timeout', models.PositiveIntegerField(default=10, verbose_name='Timeout (seconds)')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
