# Generated by Django 5.2.15 on 2026-06-11 21:34

import task_dashboard.users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_emailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Use these SSO settings. Takes precedence over the KEYCLOAK_* environment variables.', verbose_name='Enabled')),
                ('provider_name', models.CharField(default='Keycloak', help_text='Display name shown on the login button.', max_length=100, verbose_name='Provider Name')),
                ('server_url', models.URLField(blank=True, default='', help_text='OIDC issuer / realm URL, e.g. https://keycloak.example.com/realms/myrealm', max_length=255, verbose_name='Server URL')),
                ('client_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Client ID')),
                ('client_secret', task_dashboard.users.fields.EncryptedCharField(blank=True, default='', max_length=255, verbose_name='Client Secret')),
            ],
            options={
                'verbose_name': 'SSO Settings',
                'verbose_name_plural': 'SSO Settings',
            },
        ),
    ]
