# Generated by Django 5.2.15 on 2026-07-16 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_repair_empty_default_task_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServicePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='NONE', help_text='Overrides group permissions for this service. FULL: View everything. LIMITED: View only unassigned tasks or those assigned to the user. OWN: View only tasks assigned to the user. NONE: No access.', max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Service Permission',
                'verbose_name_plural': 'User Service Permissions',
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.CreateModel(
            name='UserTaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('FULL', 'Full Access (See all tasks)'), ('LIMITED', 'Limited (Own tasks + Unassigned only)'), ('OWN', 'Only own tasks'), ('NONE', 'No Access')], default='NONE', help_text='Overrides group permissions for this external group. FULL: View everything. LIMITED: View only unassigned tasks or those assigned to the user. OWN: View only tasks assigned to the user. NONE: No access.', max_length=10)),
                ('allowed_external_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.externalgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Task Permission',
                'verbose_name_plural': 'User Task Permissions',
                'unique_together': {('user', 'allowed_external_group')},
            },
        ),
    ]
