services:
  django:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/app:z  # Bind mount the root workspace
      - /app/.venv
      # Bind mount specific config files if needed
      - ~/.ssh:/home/dev-user/.ssh:ro
    env_file: ../.env
    # Keep container running for VS Code to attach
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - postgres
    # Forward ports for local browser access
    ports:
      - "8000:8000"

  postgres:
    # Use the prod DB build so we have backup scripts available in dev too
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    env_file: ../.env
    volumes:
      - dev_postgres_data:/var/lib/postgresql


volumes:
  dev_postgres_data:
