# Generated by Django 5.2.14 on 2026-05-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KimaiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_days', models.IntegerField(default=3, help_text='Business days behind before reminder triggers.', verbose_name='Grace Period (days)')),
                ('holiday_country', models.CharField(default='DE', help_text='ISO 3166-1 alpha-2 country code for public holidays (e.g. DE).', max_length=5, verbose_name='Holiday Country Code')),
                ('exempt_emails', models.TextField(blank=True, default='', help_text='Newline-separated list of emails to exclude from reminders and sync.', verbose_name='Exempt Emails')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Sync service tasks to Kimai activities.', verbose_name='Activity Sync Enabled')),
                ('team_sync_enabled', models.BooleanField(default=True, help_text='Sync Django groups to Kimai teams for activity visibility.', verbose_name='Team Sync Enabled')),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Show reminder banner when user is behind on time tracking.', verbose_name='Reminder Enabled')),
            ],
            options={
                'verbose_name': 'Kimai Settings',
                'verbose_name_plural': 'Kimai Settings',
            },
        ),
    ]
