# Generated by Django 5.2.14 on 2026-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimaisettings',
            name='customer_country',
            field=models.CharField(default='DE', help_text='ISO 3166-1 alpha-2 country code used when creating Kimai customers.', max_length=5, verbose_name='Customer Country Code'),
        ),
        migrations.AddField(
            model_name='kimaisettings',
            name='customer_timezone',
            field=models.CharField(default='Europe/Berlin', help_text='Timezone used when creating Kimai customers (e.g. Europe/Berlin).', max_length=64, verbose_name='Customer Timezone'),
        ),
    ]
