# Generated by Django 5.2.14 on 2026-05-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0002_add_customer_country_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kimaisettings',
            name='customer_country',
        ),
        migrations.RemoveField(
            model_name='kimaisettings',
            name='customer_timezone',
        ),
    ]
