# Generated by Django 5.2.14 on 2026-05-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0003_remove_customer_country_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kimaisettings',
            name='team_sync_enabled',
        ),
    ]
