# Generated by Django 5.2.14 on 2026-05-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0004_remove_team_sync_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kimaisettings',
            name='grace_period_days',
        ),
    ]
