# Generated by Django 5.2.14 on 2026-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0005_remove_kimaisettings_grace_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimaisettings',
            name='grace_period_days',
            field=models.IntegerField(default=3, help_text='Business days behind before reminder triggers.', verbose_name='Grace Period (days)'),
        ),
    ]
