# Generated by Django 5.2.14 on 2026-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0006_kimaisettings_grace_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimaisettings',
            name='reminder_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='How often to evaluate reminder status. Takes effect after saving.', verbose_name='Reminder Interval (minutes)'),
        ),
        migrations.AddField(
            model_name='kimaisettings',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text='How often to sync activities to Kimai. Takes effect after saving.', verbose_name='Sync Interval (minutes)'),
        ),
    ]
