# Generated by Django 5.2.14 on 2026-06-01 14:43

from django.db import migrations, models


def migrate_exempt_emails(apps, schema_editor):
    """Carry newline-separated exempt_emails into the exempt_owners M2M."""
    KimaiSettings = apps.get_model("kimai", "KimaiSettings")
    TaskOwner = apps.get_model("users", "TaskOwner")
    for settings in KimaiSettings.objects.all():
        emails = [
            e.strip().lower()
            for e in (settings.exempt_emails or "").splitlines()
            if e.strip()
        ]
        for email in emails:
            owner, _ = TaskOwner.objects.get_or_create(email=email)
            settings.exempt_owners.add(owner)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0007_kimaisettings_reminder_interval_minutes_and_more'),
        ('users', '0047_taskowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimaisettings',
            name='exempt_owners',
            field=models.ManyToManyField(blank=True, help_text='Task owners excluded from reminders and reminder emails.', to='users.taskowner', verbose_name='Exempt Owners'),
        ),
        migrations.AddField(
            model_name='kimaisettings',
            name='reminder_email_enabled',
            field=models.BooleanField(default=False, help_text='Send a daily email to owners who are behind on time tracking.', verbose_name='Reminder Emails Enabled'),
        ),
        migrations.AddField(
            model_name='kimaisettings',
            name='reminder_email_hour',
            field=models.PositiveIntegerField(default=7, help_text='Hour of day (0-23, server time) to send the daily reminder email.', verbose_name='Reminder Email Hour'),
        ),
        migrations.RunPython(migrate_exempt_emails, noop),
        migrations.RemoveField(
            model_name='kimaisettings',
            name='exempt_emails',
        ),
    ]
