# Generated by Django 5.2.14 on 2026-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0008_remove_kimaisettings_exempt_emails_and_more'),
        ('users', '0048_emailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kimaisettings',
            name='exempt_owners',
            field=models.ManyToManyField(blank=True, help_text='Emails (incl. discovered, not-yet-registered) excluded from reminders and reminder emails.', to='users.taskowner', verbose_name='Exempt Emails'),
        ),
    ]
