# Generated by Django 5.2.14 on 2026-06-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0009_alter_kimaisettings_exempt_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimaisettings',
            name='reminder_email_body',
            field=models.TextField(blank=True, help_text='Body of the reminder email (plain text). Leave blank for the default. Placeholders: {{ name }}, {{ days_behind }}, {{ grace_period }}, {{ kimai_url }}, {{ never_booked }}. Django template tags such as {% if never_booked %}…{% endif %} are supported.', verbose_name='Reminder Email Message'),
        ),
        migrations.AddField(
            model_name='kimaisettings',
            name='reminder_email_subject',
            field=models.CharField(blank=True, help_text='Subject line for the reminder email. Leave blank for the default. Placeholders: {{ name }}, {{ days_behind }}, {{ grace_period }}, {{ kimai_url }}, {{ never_booked }}.', max_length=255, verbose_name='Reminder Email Subject'),
        ),
    ]
