# Generated by Django 5.2.14 on 2026-06-04 17:06

from django.db import migrations, models

from task_dashboard.kimai.models import DEFAULT_REMINDER_EMAIL_BODY
from task_dashboard.kimai.models import DEFAULT_REMINDER_EMAIL_SUBJECT


def fill_blank_defaults(apps, schema_editor):
    KimaiSettings = apps.get_model("kimai", "KimaiSettings")
    KimaiSettings.objects.filter(reminder_email_subject="").update(
        reminder_email_subject=DEFAULT_REMINDER_EMAIL_SUBJECT
    )
    KimaiSettings.objects.filter(reminder_email_body="").update(
        reminder_email_body=DEFAULT_REMINDER_EMAIL_BODY
    )


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0010_kimaisettings_reminder_email_body_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_blank_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='kimaisettings',
            name='reminder_email_body',
            field=models.TextField(default='Hi {{ name }},\n\n{% if never_booked %}We have no time-tracking entries for you in Kimai yet. Please start booking your hours.{% else %}You are currently {{ days_behind }} working days behind on your time tracking in Kimai (grace period: {{ grace_period }} days).{% endif %}\n\n{% if kimai_url %}Open Kimai: {{ kimai_url }}{% endif %}\n\nThanks,\nTask Dashboard\n', help_text='Body of the reminder email (plain text). Placeholders: {{ name }}, {{ days_behind }}, {{ grace_period }}, {{ kimai_url }}, {{ never_booked }}. Django template tags such as {% if never_booked %}…{% endif %} are supported.', verbose_name='Reminder Email Message'),
        ),
        migrations.AlterField(
            model_name='kimaisettings',
            name='reminder_email_subject',
            field=models.CharField(default='{% if never_booked %}Reminder: please start tracking your time in Kimai{% else %}Reminder: you are {{ days_behind }} working days behind in Kimai{% endif %}', help_text='Subject line for the reminder email. Placeholders: {{ name }}, {{ days_behind }}, {{ grace_period }}, {{ kimai_url }}, {{ never_booked }}.', max_length=255, verbose_name='Reminder Email Subject'),
        ),
    ]
