# Generated by Django 5.2.15 on 2026-06-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimai', '0011_alter_kimaisettings_reminder_email_body_and_more'),
        ('users', '0050_repair_empty_default_task_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimaisettings',
            name='deactivation_grace_days',
            field=models.PositiveIntegerField(default=14, help_text='When a task closes, its Kimai activity is left active for this many days before being deactivated (hidden, never deleted) — so people can still book a little time after the task is closed. Set to 0 to deactivate immediately on close.', verbose_name='Deactivation Grace Period (days)'),
        ),
        migrations.CreateModel(
            name='KimaiActivityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('flagged_at', models.DateField(help_text='Date the source task was first seen closed/removed.')),
                ('deactivated', models.BooleanField(default=False, help_text='Set once the grace period elapsed and the activity was hidden.')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kimai_activity_flags', to='users.serviceconfiguration')),
            ],
            options={
                'verbose_name': 'Kimai Activity Flag',
                'verbose_name_plural': 'Kimai Activity Flags',
                'constraints': [models.UniqueConstraint(fields=('config', 'external_id'), name='unique_kimai_activity_flag_per_task')],
            },
        ),
    ]
