# Generated by Django 5.2.8 on 2025-12-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service Name (e.g. Zammad, GitLab)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this service from the dashboard completely.')),
            ],
            options={
                'verbose_name': 'Service Configuration',
                'verbose_name_plural': 'Service Configurations',
            },
        ),
    ]
