# Generated by Django 5.2.8 on 2025-12-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_serviceconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconfiguration',
            options={'ordering': ['name'], 'verbose_name': 'Service Configuration', 'verbose_name_plural': 'Service Configurations'},
        ),
        migrations.CreateModel(
            name='ExternalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['origin', 'name'],
                'unique_together': {('origin', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TicketPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_external_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.externalgroup')),
                ('django_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Ticket Permission',
                'verbose_name_plural': 'Ticket Permissions',
                'unique_together': {('django_group', 'allowed_external_group')},
            },
        ),
    ]
