# Generated by Django 5.2.8 on 2025-12-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_serviceconfiguration_options_externalgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpermission',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Full Access (See all tickets)'), ('LIMITED', 'Limited (Own tickets + Unassigned only)')], default='FULL', help_text='FULL: View everything. LIMITED: View only unassigned tickets or those assigned to the user.', max_length=10),
        ),
    ]
