# Generated by Django 5.2.8 on 2026-01-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ticketpermission_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='api_token',
            field=models.CharField(blank=True, help_text='API Token or Secret for authentication.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='api_url',
            field=models.URLField(blank=True, help_text='Base URL for the service API.', null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='service_type',
            field=models.CharField(choices=[('zammad', 'Zammad'), ('gitlab', 'GitLab'), ('espocrm', 'EspoCRM'), ('eramba', 'Eramba'), ('openproject', 'OpenProject')], default='zammad', help_text='Type of service to connect to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='name',
            field=models.CharField(help_text='Display Name (e.g. Internal Helpdesk)', max_length=50, unique=True),
        ),
    ]
