# Generated by Django 5.2.8 on 2026-01-20 17:25

import ticket_dashboard.users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_serviceconfiguration_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='api_token',
            field=ticket_dashboard.users.fields.EncryptedCharField(blank=True, help_text='API Token or Secret for authentication.', max_length=255, null=True),
        ),
    ]
